dist: trusty
language: rust
sudo: true

addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - libiberty-dev
            - g++

os:
    - linux
#   - osx

rust:
    - 1.16.0
    - 1.20.0
    - beta
    - nightly

env:
    matrix:
        - ARCH=x86_64
#       - ARCH=i686
        # ignoring 32-bit targets until a proper 32-bit environment is provided.
        # see https://github.com/travis-ci/travis-ci/issues/986

install:
    - rustc -vV
    - cargo -vV

    # Install kcov.
    - mkdir -p ~/.cargo/bin
    - sh src/install_kcov.sh
    - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
    - export RUSTFLAGS="-C link-dead-code"
    - kcov --version

script:
    - cargo build
    - cargo test

    # Note: we skip the `check-specimen` test in coverage because kcov cannot do recursive-ptrace.
    # Track this file: https://github.com/SimonKagstrom/kcov/blob/master/tests/recursive-ptrace/main.cc
    - cargo run -- kcov --verbose --no-clean-rebuild --lib --coveralls
